version: '{build}'
build_script:
  - cmd: git submodule update --init --recursive

  # Install clang-cl
  - appveyor DownloadFile http://releases.llvm.org/5.0.1/LLVM-5.0.1-win64.exe -FileName llvm-installer.exe
  - start /WAIT llvm-installer.exe /S /D=C:\"Program Files\LLVM"

  - cmd: mkdir build-14-debug && cd build-14-debug\
  - cmd: cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Debug ..\
  - cmd: cmake --build . --config Debug -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Debug\foonathan_memory_test.exe

  - cmd: cd ..\ && mkdir build-14-release && cd build-14-release\
  - cmd: cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Release ..\
  - cmd: cmake --build . --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Release\foonathan_memory_test.exe

  - cmd: cd ..\ && mkdir build-cl-debug && cd build-cl-debug\
  - cmd: cmake -G"Visual Studio 14" -T "LLVM-vs2014" -DCMAKE_BUILD_TYPE=Debug ..\
  - cmd: cmake --build . --config Debug -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Debug\foonathan_memory_test.exe

  - cmd: cd ..\ && mkdir build-cl-release && cd build-cl-release\
  - cmd: cmake -G"Visual Studio 14" -T "LLVM-vs2014" -DCMAKE_BUILD_TYPE=Release ..\
  - cmd: cmake --build . --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: test\Release\foonathan_memory_test.exe

